name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: sbt/setup-sbt@v1
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: sbt
      - name: Build and Publish
        env:
          JIB_TARGET_IMAGE_USERNAME: ${{ github.actor }}
          JIB_TARGET_IMAGE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: sbt jibImageBuild
